// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
// get user
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

//update user
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
//get All vedam
export const GET_VEDAMS_REQUEST = "GET_VEDAMS_REQUEST";
export const GET_VEDAMS_SUCCESS = "GET_VEDAMS_SUCCESS";
export const GET_VEDAMS_FAILED = "GET_VEDAMS_FAILED";
//edit vedam
export const UPDATE_VEDAMS_REQUEST = "UPDATE_VEDAMS_REQUEST";
export const UPDATE_VEDAMS_SUCCESS = "UPDATE_VEDAMS_SUCCESS";
export const UPDATE_VEDAMS_FAILED = "UPDATE_VEDAMS_FAILED";
//add vedam
export const ADD_VEDAMS_REQUEST = "ADD_VEDAMS_REQUEST";
export const ADD_VEDAMS_SUCCESS = "ADD_VEDAMS_SUCCESS";
export const ADD_VEDAMS_FAILED = "ADD_VEDAMS_FAILED";
//delete vedam
export const DELETE_VEDAMS_REQUEST = "DELETE_VEDAMS_REQUEST";
export const DELETE_VEDAMS_SUCCESS = "DELETE_VEDAMS_SUCCESS";
export const DELETE_VEDAMS_FAILED = "DELETE_VEDAMS_FAILED";

//get mandals
export const GET_MANDALS_REQUEST = "GET_MANDALS_REQUEST";
export const GET_MANDALS_SUCCESS = "GET_MANDALS_SUCCESS";
export const GET_MANDALS_FAILED = "GET_MANDALS_FAILED";
//add mandal
export const ADD_MANDAL_REQUEST = "ADD_MANDAL_REQUEST";
export const ADD_MANDAL_SUCCESS = "ADD_MANDAL_SUCCESS";
export const ADD_MANDAL_FAILED = "ADD_MANDAL_FAILED";
//update mandals
export const UPDATE_MANDAL_REQUEST = "UPDATE_MANDAL_REQUEST";
export const UPDATE_MANDAL_SUCCESS = "UPDATE_MANDAL_SUCCESS";
export const UPDATE_MANDAL_FAILED = "UPDATE_MANDAL_FAILED";
//delete mandal
export const DELETE_MANDAL_REQUEST = "DELETE_MANDAL_REQUEST";
export const DELETE_MANDAL_SUCCESS = "DELETE_MANDAL_SUCCESS";
export const DELETE_MANDAL_FAILED = "DELETE_MANDAL_FAILED";

//get suktas
export const GET_SUKTAS_REQUEST = "GET_SUKTAS_REQUEST";
export const GET_SUKTAS_SUCCESS = "GET_SUKTAS_SUCCESS";
export const GET_SUKTAS_FAILED = "GET_SUKTAS_FAILED";
//add suktas
export const ADD_SUKTAS_REQUEST = "ADD_SUKTAS_REQUEST";
export const ADD_SUKTAS_SUCCESS = "ADD_SUKTAS_SUCCESS";
export const ADD_SUKTAS_FAILED = "ADD_SUKTAS_FAILED";
//update suktas
export const UPDATE_SUKTAS_REQUEST = "UPDATE_SUKTAS_REQUEST";
export const UPDATE_SUKTAS_SUCCESS = "UPDATE_SUKTAS_SUCCESS";
export const UPDATE_SUKTAS_FAILED = "UPDATE_SUKTAS_FAILED";
//delete suktas
export const DELETE_SUKTAS_REQUEST = "DELETE_SUKTAS_REQUEST";
export const DELETE_SUKTAS_SUCCESS = "DELETE_SUKTAS_SUCCESS";
export const DELETE_SUKTAS_FAILED = "DELETE_SUKTAS_FAILED";

//add mantras
export const ADD_MANTRA_REQUEST = "ADD_MANTRA_REQUEST";
export const ADD_MANTRA_SUCCESS = "ADD_MANTRA_SUCCESS";
export const ADD_MANTRA_FAILED = "ADD_MANTRA_FAILED";
//get mantras
export const GET_MANTRA_REQUEST = "GET_MANTRA_REQUEST";
export const GET_MANTRA_SUCCESS = "GET_MANTRA_SUCCESS";
export const GET_MANTRA_FAILED = "GET_MANTRA_FAILED";
//update mantras
export const UPDATE_MANTRA_REQUEST = "UPDATE_MANTRA_REQUEST";
export const UPDATE_MANTRA_SUCCESS = "UPDATE_MANTRA_SUCCESS";
export const UPDATE_MANTRA_FAILED = "UPDATE_MANTRA_FAILED";
//delete mantras
export const DELETE_MANTRA_REQUEST = "DELETE_MANTRA_REQUEST";
export const DELETE_MANTRA_SUCCESS = "DELETE_MANTRA_SUCCESS";
export const DELETE_MANTRA_FAILED = "DELETE_MANTRA_FAILED";

//add tags
export const ADD_TAGS_REQUEST = "ADD_TAGS_REQUEST";
export const ADD_TAGS_SUCCESS = "ADD_TAGS_SUCCESS";
export const ADD_TAGS_FAILED = "ADD_TAGS_FAILED";
//get tags
export const GET_TAGS_REQUEST = "GET_TAGS_REQUEST";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAILED = "GET_TAGS_FAILED";
//update tags
export const UPDATE_TAGS_REQUEST = "UPDATE_TAGS_REQUEST";
export const UPDATE_TAGS_SUCCESS = "UPDATE_TAGS_SUCCESS";
export const UPDATE_TAGS_FAILED = "UPDATE_TAGS_FAILED";
//update tags
export const DELETE_TAGS_REQUEST = "DELETE_TAGS_REQUEST";
export const DELETE_TAGS_SUCCESS = "DELETE_TAGS_SUCCESS";
export const DELETE_TAGS_FAILED = "DELETE_TAGS_FAILED";

//add mantraTag
export const ADD_MANTRTAG_REQUEST = "ADD_MANTRTAG_REQUEST";
export const ADD_MANTRTAG_SUCCESS = "ADD_MANTRTAG_SUCCESS";
export const ADD_MANTRTAG_FAILED = "ADD_MANTRTAG_FAILED";
//get mantraTag
export const GET_MANTRTAG_REQUEST = "GET_MANTRTAG_REQUEST";
export const GET_MANTRTAG_SUCCESS = "GET_MANTRTAG_SUCCESS";
export const GET_MANTRTAG_FAILED = "GET_MANTRTAG_FAILED";
//update mantraTag
export const UPDATE_MANTRTAG_REQUEST = "UPDATE_MANTRTAG_REQUEST";
export const UPDATE_MANTRTAG_SUCCESS = "UPDATE_MANTRTAG_SUCCESS";
export const UPDATE_MANTRTAG_FAILED = "UPDATE_MANTRTAG_FAILED";
//update mantraTag
export const DELETE_MANTRTAG_REQUEST = "DELETE_MANTRTAG_REQUEST";
export const DELETE_MANTRTAG_SUCCESS = "DELETE_MANTRTAG_SUCCESS";
export const DELETE_MANTRTAG_FAILED = "DELETE_MANTRTAG_FAILED";
